php:
  preset: laravel
  version: 8
  disabled:
    - no_unused_imports
  finder:
    not-name:
      - index.php
<<<<<<< HEAD
      - server.php
=======
>>>>>>> main
js:
  finder:
    not-name:
      - webpack.mix.js
css: true
